app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, DateField
from wtforms.validators import Length, ValidationError, DataRequired
from flask_wtf.file import FileField, FileRequired, FileAllowed
from flask import abort, current_app

import requests
import phonenumbers

from ..models import User, Role


class EditProfileForm(FlaskForm):
    fname = StringField("First Name", validators=[Length(
        0, 30)], render_kw={"placeholder": "First Name"})
    lname = StringField("Last Name", validators=[Length(
        0, 30)], render_kw={"placeholder": "Last Name"})
    address = StringField('Address', validators=[Length(
        0, 30)], render_kw={"placeholder": "Address"})
    state = SelectField("State", coerce=str)
    city = SelectField('City', coerce=str)
    country = StringField('Country', validators=[Length(
        0, 30)], render_kw={"placeholder": "Country"})
    zipcode = StringField('Zip Code', validators=[Length(
        0, 30)], render_kw={"placeholder": "Zip Code"})
    phone = StringField('Phone Number', validators=[
                        Length(0, 20)], render_kw={"placeholder": "Phone"})
    submit = SubmitField("Edit")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.state.choices = [('0', "--Select State--")] + [(prov['province'],
                                                             prov['province']) for prov in self.get_province()]
        self.city.choices = [("0", "-- Select City --")] + \
            [(city['city_name'], city['city_name'])
             for city in self.get_cities()]

    def get_province(self):
        try:
            r = requests.get('https://api.rajaongkir.com/starter/province', headers={
                "key": current_app.config['KEY']
            })
        except requests.exceptions.RequestException as e:
            abort(500)

        province_list = r.json()['rajaongkir'].get('results')
        return province_list

    def get_cities(self):
        try:
            r = requests.get('https://api.rajaongkir.com/starter/city', headers={
                "key": current_app.config['KEY']
            })
        except requests.exceptions.RequestException as e:
            abort(500)

        cities = r.json()['rajaongkir'].get('results')
        return cities

    def validate_phone(self, field):
        try:
            p = phonenumbers.parse(f"+{field.data}")
            if not phonenumbers.is_valid_number(p):
                raise ValueError()
        except (phonenumbers.phonenumberutil.NumberParseException, ValueError):
            raise ValidationError("Invalid Phone Number.")


class EditProfileAdminForm(FlaskForm):
    fname = StringField("First Name", validators=[Length(
        0, 30)], render_kw={"placeholder": "First Name"})
    lname = StringField("Last Name", validators=[Length(
        0, 30)], render_kw={"placeholder": "Last Name"})
    address = StringField('Address', validators=[Length(
        0, 30)], render_kw={"placeholder": "Address"})
    state = SelectField('State', coerce=str)
    city = SelectField('City', coerce=str)
    country = StringField('Country', validators=[Length(
        0, 30)], render_kw={"placeholder": "Country"})
    zipcode = StringField('Zip Code', validators=[Length(
        0, 30)], render_kw={"placeholder": "Zip Code"})
    phone = StringField('Phone Number', validators=[
                        Length(0, 20)], render_kw={"placeholder": "Phone"})
    role = SelectField("Role", coerce=int)
    submit = SubmitField("Edit")

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.role.choices = [(0, "-- Select Role --")] + [(role.id, role.name)
                                                          for role in Role.query.order_by(Role.name).all()]
        self.state.choices = [('0', "-- Select State --")] + \
            [(prov['province'], prov['province'])
             for prov in self.get_province()]
        self.city.choices = [("0", "-- Select City --")] + \
            [(city['city_name'], city['city_name'])
             for city in self.get_cities()]

    def get_province(self):
        try:
            r = requests.get('https://api.rajaongkir.com/starter/province', headers={
                "key": current_app.config['KEY']
            })
        except requests.exceptions.RequestException as e:
            abort(500)

        province_list = r.json()['rajaongkir'].get('results')
        return province_list

    def get_cities(self):
        try:
            r = requests.get('https://api.rajaongkir.com/starter/city', headers={
                "key": current_app.config['KEY']
            })
        except requests.exceptions.RequestException as e:
            abort(500)

        cities = r.json()['rajaongkir'].get('results')
        return cities

    def validate_phone(self, field):
        try: 
            p = phonenumbers.parse(f"+{field.data}")
            if not phonenumbers.is_valid_number(p):
                raise ValueError()
        except (phonenumbers.phonenumberutil.NumberParseException, ValueError):
            raise ValidationError("Invalid Phone Number.")


# field generated by open ai
class ProofOfPaymentForm(FlaskForm):
    # the name of the person or entity making the payment
    payer = StringField("From", validators=[DataRequired()])
    # the date that the payment made
    date = DateField("Date", validators=[DataRequired()])
    # the method to make the payment, such as cash, check, or credit card, etc.
    payment_method = SelectField('Payment via', choices=[("0", "--Pilih Pembayaran"), ("dana", "Dana"), ("ovo", "OVO"), ("gopay", "GoPay"), ("bri", "BRI")])
    image = FileField("select image...", validators=[FileRequired(), FileAllowed(["jpg", "png", "jpeg"], "Images Only!")])
    submit = SubmitField('Send')

app/users/__init__.py
from flask import Blueprint

users = Blueprint("users", __name__)

from . import views

app/users/views.py
import os.path

from flask_login import login_required
from flask import render_template, flash, redirect, url_for, current_app, abort, jsonify
from flask_login import current_user
from datetime import datetime
from werkzeug.utils import secure_filename

import requests

from . import users
from .. import db
from ..decorators import admin_required
from .forms import EditProfileForm, EditProfileAdminForm, ProofOfPaymentForm
from ..models import User, Role, Orders, ProofOfPayment


@users.get('/')
@login_required
@admin_required
def user_list():
    users = User.query.all()
    return render_template('users/user_list.html', users=users)


@users.get('/me')
@login_required
def user_profile():
    user = User.query.filter_by(id=current_user.id).first()
    return render_template('users/profile.html', user=user)


@ users.get('/edit')
@ users.post('/edit')
@ login_required
def edit_profile():
    form = EditProfileForm()
    user = User.query.filter_by(id=current_user.id).first()

    if form.validate_on_submit():
        user.fname = form.fname.data
        user.lname = form.lname.data
        user.address = form.address.data
        user.city = form.city.data
        user.state = form.state.data
        user.country = form.country.data
        user.zipcode = form.zipcode.data
        user.phone = form.phone.data
        user.updated_at = datetime.utcnow()

        db.session.commit()
        flash("User update successfully!!")
        return redirect(url_for('users.user_profile'))

    form.fname.data = user.fname
    form.lname.data = user.lname
    form.address.data = user.address
    form.city.data = user.city
    form.state.data = user.state
    form.country.data = user.country
    form.zipcode.data = user.zipcode
    form.phone.data = user.phone
    return render_template('users/edit_profile.html', form=form, user=user, key=current_app.config['KEY'])


@ users.get('/<int:id>/edit')
@ users.post('/<int:id>/edit')
@ login_required
@ admin_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user)

    if form.validate_on_submit():
        user.fname = form.fname.data
        user.lname = form.lname.data
        user.address = form.address.data
        user.city = form.city.data
        user.state = form.state.data
        user.country = form.country.data
        user.zipcode = form.zipcode.data
        user.phone = form.phone.data
        user.role = Role.query.get(form.role.data)
        user.updated_at = datetime.utcnow()

        db.session.commit()
        flash("User update successfully!!")
        return redirect(url_for('users.user_list'))

    form.fname.data = user.fname
    form.lname.data = user.lname
    form.address.data = user.address
    form.city.data = user.city
    form.state.data = user.state
    form.country.data = user.country
    form.zipcode.data = user.zipcode
    form.phone.data = user.phone
    form.role.data = user.role_id
    return render_template('users/edit_profile_admin.html', form=form, user=user)


@ users.get('/<int:id>/delete')
@ login_required
@ admin_required
def user_delete(id):
    user = User.query.get_or_404(id)
    db.session.delete(user)
    db.session.commit()
    flash("User delete successfully.")


@users.get('/get_provinces')
def get_user_province():
    try:
        r = requests.get('https://api.rajaongkir.com/starter/province', headers={
            "key": current_app.config['KEY']
        })
    except requests.exceptions.RequestException as e:
        abort(500)

    provinces = r.json()['rajaongkir']['results']
    return jsonify(provinces)


@users.get('/get_cities/<province_id>')
def get_cities(province_id):
    try:
        r = requests.get(
            f'https://api.rajaongkir.com/starter/city?province={province_id}', headers={
                "key": current_app.config['KEY']
            })
    except requests.exceptions.RequestException as e:
        abort(500)

    cities = r.json()['rajaongkir']['results']
    return jsonify(cities)


@users.get('/transaction-history')
@login_required
def history():
    orders = Orders.query.filter_by(customer_id=current_user.id).all()
    return render_template('users/history.html', orders=orders)


# proof of payment
@users.get('/paying/<int:id>')
@users.post('/paying/<int:id>')
@login_required
def proof_of_payment(id):
    form = ProofOfPaymentForm()
    UPLOAD_DIR = os.path.join(current_app.config['UPLOAD_FOLDER'], "transaction_image")

    if not os.path.exists(UPLOAD_DIR):
        os.makedirs(UPLOAD_DIR)

    order = Orders.query.get(id)

    if form.validate_on_submit():
        try:
            payer, date, payment_method, image = form.payer.data,form.date.data, form.payment_method.data, form.image.data
            filename = secure_filename(image.filename)
            pop = ProofOfPayment(date=date, payer=payer, payment_method=payment_method, proof_of_payment=filename, paying=order)
            image.save(os.path.join(UPLOAD_DIR, filename))

            order.status = "capture"

            db.session.add(pop)
            db.session.commit()

            flash("Submit proof of successful payment. please wait for confirmation from the store. thank you!!", "success")
            return redirect(url_for("users.history"))

        except:
            abort(500)


    return render_template("proof_of_pay.html", form=form)


@users.get('/pop_details/<int:id>')
@login_required
@admin_required
def pop_details(id):
    try:
        order = Orders.query.get(id)
        pop_ = order.proof_of_payment
        return render_template('pop_details.html', pop=pop_)
    except:
        abort(500)


@users.get('/<int:id>/accept')
@login_required
@admin_required
def onAccept(id):
    try:
        order = Orders.query.get(id  )
        order.status = "success"
        db.session.commit()
        return redirect(url_for("users.orders"))
    except:
        abort(404)


@users.get('/<int:id>/decline')
@login_required
@admin_required
def onDecline(id):
    try:
        order = Orders.query.get(id)
        order.status = "cancel"
        db.session.commit()
        return redirect(url_for("users.orders"))
    except:
        abort(404)

app/templates/users/edit_profile.html
{% extends "base.html" %}

{% block content %}

  <div class="container mt-5 w-50 pb-5">
    <h1 class="font-weight-bold">Profile</h1>
    <hr>

    <div class="mt-4 w-75 mx-auto">

      {# card #}
        <div class="card">
          <div class="card-header">
            <h5 class="card-title font-weight-light">Your Profile</h5>
          </div>

          <form method="post">
            {{form.hidden_tag()}}
            <div class="card-body">
              <div class="form-row">
                <div class="form-group col-md-6">
                  {{form.fname.label}}
                  {{form.fname(class="form-control")}}
                </div>
                <div class="form-group col-md-6">
                  {{form.lname.label}}
                  {{form.lname(class="form-control")}}
                </div>
              </div>
              <div class="form-group">
                {{form.address.label}}
                {{form.address(class="form-control")}}
              </div>
              <div class="form-group">
                {{form.city.label}}
                {{form.city(class="form-control")}}
              </div>
              <div class="form-group">
                {{form.state.label}}
                {{form.state(class="form-control")}}
              </div>
              <div class="form-group">
                {{form.country.label}}
                {{form.country(class="form-control")}}
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  {{form.zipcode.label}}
                  {{form.zipcode(class="form-control")}}
                </div>
                <div class="form-group col-md-6">
                  {{form.phone.label}}
                  {{form.phone(class="form-control")}}
                  {% for error in form.phone.errors %}
                    <small id="passwordHelp" class="text-danger">
                      {{error}}
                    </small>      
                  {% endfor %}
                </div>
              </div>

              {{form.submit(class="btn btn-info btn-block")}}
              <button class="btn btn-secondary btn-block" onclick="history.back()">Back</button>
            </div>
          </div>
        {# end card #}
        
      </div>
    </form>

  </div>  

{% endblock content %}

app/templates/users/edit_profile_admin.html
{% extends "base.html" %}

{% block content %}

  <div class="container mt-5 w-50 pb-5">
    <h1 class="font-weight-bold">Edit Profile Admin</h1>
    <hr>

    <div class="mt-4 w-75 mx-auto">

      {# card #}
        <div class="card">
          <div class="card-header">
            <h5 class="card-title font-weight-light">{{ user.fname|title }} Profile</h5>
          </div>

          <form method="post">
            {{form.hidden_tag()}}
            <div class="card-body">
              <div class="form-row">
                <div class="form-group col-md-6">
                  {{form.fname.label}}
                  {{form.fname(class="form-control")}}
                </div>
                <div class="form-group col-md-6">
                  {{form.lname.label}}
                  {{form.lname(class="form-control")}}
                </div>
              </div>
              <div class="form-group">
                {{form.address.label}}
                {{form.address(class="form-control")}}
              </div>
              <div class="form-group">
                {{form.city.label}}
                {{form.city(class="form-control")}}
              </div>
              <div class="form-group">
                {{form.state.label}}
                {{form.state(class="form-control")}}
              </div>
              <div class="form-group">
                {{form.country.label}}
                {{form.country(class="form-control")}}
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  {{form.zipcode.label}}
                  {{form.zipcode(class="form-control")}}
                </div>
                <div class="form-group col-md-6">
                  {{form.phone.label}}
                  {{form.phone(class="form-control")}}
                  {% for error in form.phone.errors %}
                    <small id="passwordHelp" class="text-danger">
                      {{error}}
                    </small>      
                  {% endfor %}
                </div>
                <div class="form-group">
                  {{form.role.label}}
                  {{form.role(class="form-control")}}
                </div>
              </div>

              {{form.submit(class="btn btn-info btn-block")}}
              <button class="btn btn-secondary btn-block" onclick="history.back()">Back</button>
            </div>
          </div>
        {# end card #}
        
      </div>
    </form>

  </div>  

{% endblock content %}

app/templates/users/history.html
{% from 'bootstrap4/utils.html' import render_icon %}

{% extends "base.html" %}

{% block content %}

  <div class="container mt-5 w-50 pb-5">
    <h1 class="font-weight-bold">Transaction History</h1>
    <hr>

      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            {% if orders|length < 1 %}
              <div class="alert alert-danger" role="alert">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                  <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                Order Transaction is Empty!!
              </div>
            {% else %}

            <table class="table">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Penerima</th>
                  <th>Alamat</th>
                  <th>Status</th>
                  <th>&nbsp;</th>
                </tr>
              </thead>
              <tbody>
                {% for order in orders %}  
                <tr>
                  <td>{{ loop.index }}</td>
                  <td>{{ order.penerima }}</td>
                  <td>{{ order.alamat }}</td>
                  <td>
                    <span class="badge badge-{% if order.status == 'pending' %}warning{% elif order.status == 'expired' %}info{%elif order.status == 'success' %}success{% else %}danger{% endif %}">{{order.status}}</span>
                  </td>
                  <td>
                    <a href="{{ url_for('main.invoice', id=order.id) }}" class="btn btn-sm btn-warning">{{ render_icon('file-earmark-text-fill') }}</a>
                    {% if order.status == "pending" %}
                      <a href="{{ url_for('main.cancel_order', id=order.id) }}" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Cancel Order">{{ render_icon("x-circle-fill") }}</a>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% endif %}
          </div>
        </div>
      </div>

  </div>  

{% endblock content %}

app/templates/users/profile.html
{% extends "base.html" %}

{% block content %}

  <div class="container mt-5 w-50 pb-5">
    <h1 class="font-weight-bold">Profile</h1>
    <hr>
    <div class="m-0 p-3">
      <img src="{{ current_user.avatar(145) }}" class="rounded-circle mx-auto d-block" alt="Profile">
    </div>

    <div class="mt-4 w-75 mx-auto">

      {# card #}
        <div class="card">
          <div class="card-header">
            <h5 class="card-title font-weight-light">Your Profile</h5>
          </div>
          <div class="card-body">
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="firstName">First Name</label>
                <input type="text" class="form-control text-muted" id="firstName" value="{{ user.fname }}" placeholder="First Name" disabled>
              </div>
              <div class="form-group col-md-6">
                <label for="firstName">Last Name</label>
                <input type="text" class="form-control text-muted" id="lastName" value="{{ user.lname }}" placeholder="Last Name" disabled>
              </div>
            </div>
            <div class="form-group">
              <label for="firstName">Address</label>
              <input type="text" class="form-control text-muted" id="address" value="{{ user.address }}" disabled placeholder="Address">
            </div>
            <div class="form-group">
              <label for="firstName">City</label>
              <input type="text" class="form-control text-muted" id="city" value="{{ user.city }}" placeholder="City" disabled>
            </div>
            <div class="form-group">
              <label for="firstName">State</label>
              <input type="text" class="form-control text-muted" id="city" value="{{ user.state }}" placeholder="State" disabled>
            </div>
            <div class="form-group">
              <label for="firstName">Country</label>
              <input type="text" class="form-control text-muted" id="city" value="{{ user.country }}" placeholder="Country" disabled>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="firstName">Zip Code</label>
                <input type="text" class="form-control text-muted" id="zipCode" value="{{ user.zipcode }}" placeholder="Zip Code"  disabled>
              </div>
              <div class="form-group col-md-6">
                <label for="firstName">Phone Number</label>
                <input type="text" class="form-control text-muted" id="phone" value="{{ user.phone }}" placeholder="Phone Number"  disabled>
              </div>
            </div>

            <a href="#back" class="btn btn-light btn-block">Change Password</a>
            <a href="{{ url_for('users.edit_profile') }}" class="btn btn-info btn-block">Edit</a>
          </div>
        </div>
      {# end card #}
      
    </div>

  </div>  

{% endblock content %}

app/templates/users/user_list.html
{% from 'bootstrap4/utils.html' import render_icon %}

{% extends "base.html" %}

{% block content %}
  <div class="container mt-5 pb-5">
    <h1 class="font-weight-bold ml-2">List User</h1>
    <hr>
    
    <div class="table-responsive">
      <table id="data" class="table table-hover">
        <caption>List of User</caption>
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Email</th>
            <th scope="col">Address</th>
            <th scope="col">Phone</th>
            <th scope="col">Role</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
            <tr>
              <td>{{ loop.index }}</td>
              <td>{{ user.email }}</td>
              <td>{{ user.address }}</td>
              <td>{{ user.phone }}</td>
              <td>{{ user.role.name }}</td>
              <td>
                <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Detail Product">
                  <a href="{{ url_for('users.edit_profile_admin', id=user.id) }}" class="btn btn-sm btn-info">{{ render_icon('file-earmark-richtext-fill') }}</a>
                </span>
                <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Delete Product">
                  <a href="{{ url_for('users.user_delete', id=user.id) }}" class="btn btn-sm btn-danger">{{ render_icon('trash-fill') }}</a>
                </span>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}