app/products/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError
from wtforms.widgets import NumberInput
from flask_ckeditor import CKEditorField

from ..models import Product
from ..utility.better_decimal_field import BetterDecimalField


class ProductForm(FlaskForm):
    sku = StringField("Sku", validators=[
                      DataRequired(), Length(1, 50)])
    product_name = StringField("Product Name", validators=[
                               DataRequired(), Length(0, 100)])
    description = CKEditorField("Description", validators=[DataRequired()])
    image = FileField("Select Product Image...", validators=[
        FileRequired(), FileAllowed(['png', 'jpg', 'jpeg'], 'png/jpg/jpeg Only!')])
    quantity = StringField("Quantity", validators=[
                           DataRequired()], widget=NumberInput(min=0))
    regular_price = BetterDecimalField('Price', validators=[DataRequired()])
    category = StringField('Category', validators=[DataRequired()])
    submit = SubmitField("Add Product")

    def validate_sku(self, field):
        sku = Product.query.filter_by(sku=field.data).first()
        if sku:
            raise ValidationError("Sku is available")


class EditProductForm(FlaskForm):
    sku = StringField("Sku", validators=[
                      DataRequired(), Length(1, 50)])
    product_name = StringField("Product Name", validators=[
                               DataRequired(), Length(0, 100)])
    description = CKEditorField("Desctiption", validators=[
                                DataRequired()])
    image = FileField("Select Product Image...")
    quantity = StringField("Quantity", validators=[
                           DataRequired()], widget=NumberInput(min=0))
    regular_price = BetterDecimalField("Price", validators=[DataRequired()])
    submit = SubmitField("Edit Product")

app/products/__init__.py
from flask import Blueprint

products = Blueprint("products", __name__)

from . import views

app/products/views.py
from flask import request, render_template, current_app, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from datetime import datetime

import os

from .. import db
from ..decorators import permission_required
from . import products
from ..models import Permission, Product, User, Category
from .forms import ProductForm, EditProductForm


@products.get('/')
@login_required
@permission_required(Permission.PRODUCT_MANAGEMENT)
def show_product():
    products = Product.query.all()
    return render_template('products/product.html', products=products)


@products.post('/add')
@products.get('/add')
@login_required
@permission_required(Permission.PRODUCT_MANAGEMENT)
def insert_product():
    form = ProductForm()
    UPLOAD_DIR = current_app.config['UPLOAD_FOLDER']

    if form.validate_on_submit():
        f = form.image.data
        filename = f"product-img-{form.sku.data}-{f.filename}"
        new_filename = secure_filename(filename)

        if not os.path.exists(UPLOAD_DIR):
            os.makedirs(UPLOAD_DIR)

        f.save(os.path.join(
            current_app.config['UPLOAD_FOLDER'], new_filename))

        categories = form.category.data.split(',')
        products_category = []
        for category in categories:
            categorys = category.strip()
            products_category.append(categorys)
            if not Category.query.filter_by(name=categorys).first():
                new_category = Category(name=categorys)
                db.session.add(new_category)

            continue

        new_product = Product(sku=form.sku.data, product_name=form.product_name.data, description=form.description.data,
                              image=new_filename, quantity=form.quantity.data, regural_price=form.regular_price.data)

        for pc in products_category:
            ct = Category.query.filter_by(name=pc).first()
            new_product.category.append(ct)

            db.session.add(new_product)

        db.session.commit()
        flash("New Product has been added")

        return redirect(url_for('products.show_product'))

    return render_template('products/add_product.html', form=form)


@products.get('/<int:id>/edit')
@products.post('/<int:id>/edit')
@login_required
@permission_required(Permission.PRODUCT_MANAGEMENT)
def edit_product(id):
    UPLOAD_DIR = current_app.config['UPLOAD_FOLDER']
    form = EditProductForm()
    products = db.get_or_404(Product, id)

    if form.validate_on_submit():
        if form.image.data:
            f = form.image.data
            head, tail = os.path.split(f.filename)
            new_filename = secure_filename(
                f"product-img-{form.sku.data}-{tail}")

            if not os.path.exists(UPLOAD_DIR):
                os.makedirs(UPLOAD_DIR)

            f.save(os.path.join(UPLOAD_DIR, new_filename))

            products.image = new_filename

        products.sku = form.sku.data
        products.product_name = form.product_name.data
        products.description = form.description.data
        products.quantity = form.quantity.data
        products.regural_price = form.regular_price.data
        products.updated_at = datetime.utcnow()

        db.session.commit()
        flash("Product update successfully")
        return redirect(url_for('products.show_product'))

    form.sku.data = products.sku
    form.product_name.data = products.product_name
    form.description.data = products.description
    form.quantity.data = products.quantity
    form.regular_price.data = products.regural_price
    form.image.data = products.image

    image_path = os.path.join(UPLOAD_DIR, products.image)
    return render_template('products/edit_product.html', form=form, products=products, image_path=image_path)


@products.get('/<int:id>/detail')
@login_required
def detail_product(id):
    product = db.get_or_404(Product, id)
    all_product = Product.query.all()
    return render_template('products/detail_product.html', product=product, all_product=all_product)


@products.get('/<int:id>/delete')
@login_required
@permission_required(Permission.PRODUCT_MANAGEMENT)
def delete_product(id):
    UPLOAD_DIR = current_app.config['UPLOAD_FOLDER']
    product = db.get_or_404(Product, id)

    path = os.path.join(UPLOAD_DIR, product.image)
    if os.path.exists(path):
        os.remove(path)

    db.session.delete(product)
    db.session.commit()
    flash("Product delete successfully.")
    return redirect(url_for('products.show_product'))

app/templates/products/add_product.html
{% extends "base.html" %}

{% block styles %}
  {{ckeditor.load()}}
{% endblock styles %}

{% block content %}

  <div class="container mt-5 w-50 pb-5">
    <h1 class="font-weight-bold">Add Product</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
      {{form.hidden_tag()}}
      <div class="form-group">
        {{form.sku.label}}
        {{form.sku(class="form-control")}}
        
        {% for error in form.sku.errors %}
        <div class="col-sm-3">
          <small id="passwordHelp" class="text-danger">
            {{error}}
          </small>      
        </div>
        {% endfor %}
      </div>
      <div class="form-group">
        {{form.product_name.label}}
        {{form.product_name(class="form-control")}}

        {% for error in form.product_name.errors %}
        <div class="col-sm-3">
          <small id="passwordHelp" class="text-danger">
            {{error}}
          </small>      
        </div>
        {% endfor %}
      </div>
      <div class="form-group">
        {{form.description.label}}
        {{form.description(class="form-control", rows="10")}}
      </div>
      <div class="form-group">
        <div class="custom-file">

          {{form.image(class="custom-file-input", id="input-file")}}
          {{form.image.label(class="custom-file-label", for="input-file")}}
          {% for error in form.image.errors %}
           <div class="col-sm-3">
              <small id="passwordHelp" class="text-danger">
                {{error}}
              </small>      
            </div>
          {% endfor %}
        </div>  
      </div>
      <div class="row">
        <div class="form-group col-md-6">
          {{form.quantity.label}}
          {{form.quantity(class="form-control")}}
        </div>
        <div class="form-group col-md-6">
          {{form.regular_price.label}}
          {{form.regular_price(class="form-control")}}
        </div>
      </div>
      <div class="form-group">
        {{form.category.label}}
        {{form.category(class="form-control", rows="10")}}
        <small id="emailHelp" class="form-text text-muted ml-2"><b>**</b> Gunakan tanda koma <code>`,`</code>untuk memisah antar kategori.</small>
      </div>
      <div class="mt-3">
        <button onclick="history.back()" class="btn btn-secondary">Back</button>
        {{form.submit(class="btn btn-success")}}
      </div>
    </form>
  </div>

{% endblock content %}

{% block scripts %}
  <script src="{{ url_for('static', filename='js/inputFile.js') }}"></script>
{% endblock scripts %}  

app/templates/products/detail_product.html
{% from 'bootstrap4/utils.html' import render_icon %}

{% extends "base.html" %}

{% block content %}
  <div class="container mt-5 w-75 pb-5">
    <h1 class="font-weight-bold ml-2">Detail Product</h1>
    <hr>

    <div class="row">
      <div class="col-md-6 px-4">
        <img src="{{ url_for('static', filename="uploads/"+ product.image) }}" alt="Image Product" class="img-responsive img-thumbnail">
      </div>
      <div class="col-md-6">
        <blockquote class="blockquote p-3">
          <p class="mb-0 h3 font-weight-bold">{{ product.product_name|title }}</p>
          <footer class="blockquote-footer">Rp. {{ product.regural_price|currency_format}}</footer>
        </blockquote>

        <table class="table table-bordered mb-5">
          <tbody>
            <tr>
              <th class="text-right">SKU</th>
              <td>{{product.sku}}</td>
            </tr>
            <tr>
              <th class="text-right">Product Name</th>
              <td>{{ product.product_name|title }}</td>
            </tr>
            <tr>
              <th class="text-right">Stok</th>
              <td>{{ product.quantity }}</td>
            </tr>
            <tr>
              <th class="text-right">Price</th>
              <td>Rp. {{ product.regural_price|currency_format }}</td>
            </tr>
          </tbody>
        </table>

        {# tabs #}
         <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item" role="presentation">
            <button class="nav-link active" id="home-tab" data-toggle="tab" data-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Description</button>
          </li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            <div class="p-3">
              <p>
                {{product.description | safe}}
              </p>
            </div>
          </div>
        </div>
        {# close tabs #}

      {% if current_user.is_administrator() %}
        <a href="{{ url_for('products.edit_product', id=product.id) }}" class="btn btn-info btn-block mb-2">Edit</a>      
      {% endif %}

        
      {% if product in current_user.products %}
        <button class="btn btn-danger btn-block" onclick="removeFromCart({{product.id}})">Remove from Cart</button>
      {% else %}
        <button class="btn btn-warning btn-block" onclick="addToCart({{product.id}})">Add to Cart</button>
      {% endif %}

        <button onclick="history.back()" class="btn btn-secondary btn-block">Back</button>

      </div>
    </div> 

  </div>
{% endblock content %}


{% block scripts %}
  <script src="{{ url_for('static', filename="js/cart.js") }}"></script>
{% endblock scripts %}

app/templates/products/edit_product.html
{% extends "base.html" %}

{% block styles %}
  {{ckeditor.load()}}
{% endblock styles %}

{% block content %}

  <div class="container mt-5 w-50 pb-5">
    <h1 class="font-weight-bold">Edit Product</h1>
    <hr>
    <form method="post"  enctype="multipart/form-data">
      {{form.hidden_tag()}}
      <div class="form-group">
        {{form.sku.label}}
        {{form.sku(class="form-control")}}
        
        {% for error in form.sku.errors %}
        <div class="col-sm-3">
          <small id="passwordHelp" class="text-danger">
            {{error}}
          </small>      
        </div>
        {% endfor %}
      </div>
      <div class="form-group">
        {{form.product_name.label}}
        {{form.product_name(class="form-control")}}

        {% for error in form.product_name.errors %}
        <div class="col-sm-3">
          <small id="passwordHelp" class="text-danger">
            {{error}}
          </small>      
        </div>
        {% endfor %}
      </div>
      <div class="form-group">
        {{form.description.label}}
        {{form.description(class="form-control", rows="10")}}
      </div>
      <div class="form-group">
        <div class="custom-file">
          {{form.image(class="custom-file-input", id="input-file", title="")}}
          {{form.image.label(class="custom-file-label", for="input-file")}}
        </div>  
      </div>
      <div class="row">
        <div class="form-group col-md-6">
          {{form.quantity.label}}
          {{form.quantity(class="form-control")}}
        </div>
        <div class="form-group col-md-6">
          {{form.regular_price.label}}
          {{form.regular_price(class="form-control")}}
        </div>
      </div>
      <div class="mt-3">
        <button onclick="history.back()" class="btn btn-danger">Back</button>
        {{form.submit(class="btn btn-success")}}
      </div>
    </form>
  </div>

{% endblock content %}

{% block scripts %}

  <script>
    let path = "{{ image_path }}"
    let filename = path.replace(/^.*[\\\/]/, '')

    // replace the choose file label
    $(".custom-file-label").html(filename);
  </script>

  <script src="{{ url_for('static', filename="js/inputFile.js") }}"></script>

{% endblock scripts %}

app/templates/products/product.html
{% from 'bootstrap4/utils.html' import render_icon %}

{% extends "base.html" %}

{% block content %}
  <div class="container mt-5 pb-5">
    <h1 class="font-weight-bold ml-2">All Product</h1>
    <hr>

    <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Add Product">
      <a href="{{ url_for('products.insert_product') }}" class="btn btn-sm btn-success mb-3 ml-2">{{ render_icon("plus-circle-fill") }}</a>
    </span>
    
    <div class="table-responsive">
      <table id="data" class="table table-hover">
        <caption>List of Product</caption>
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
            <tr>
              <td>{{ loop.index }}</td>
              <td>{{ product.product_name|title }}</td>
              <td>{{ product.quantity }}</td>
              <td>Rp.{{ product.regural_price | currency_format }}</td>
              <td>
                <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Detail Product">
                  <a href="{{ url_for('products.detail_product', id=product.id) }}" class="btn btn-sm btn-info">{{ render_icon('file-earmark-richtext-fill') }}</a>
                </span>
                <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Delete Product">
                  <a href="{{ url_for('products.delete_product', id=product.id) }}" class="btn btn-sm btn-danger">{{ render_icon('trash-fill') }}</a>
                </span>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}